### ISSUE TITLE
igprof locks up with TBB programs

### ISSUE THREAD

**Issue by ktf** [igprof/igprof#10]
From Chris.

I'm getting pretty much constant lockups of igprof when trying to look at a TBB based program. I attached to the process and did a stack trace and see
#0 0x000000344740dff4 in __lll_lock_wait () from /lib64/libpthread.so.0
#1 0x0000003447409328 in _L_lock_854 () from /lib64/libpthread.so.0
#2 0x00000034474091f7 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3 0x00007f84135c29f6 in igprof_reset_profiles () at /build/davidlt/ext/CMSSW_6_0_X/20120314_1407/a/BUILD/slc5_amd64_gcc470/external/igprof/5.9.3/igprof-5.9.3/src/profile.cc:598
#4 0x00007f84135c8c21 in dofork(IgHook::SafeData<int()> &, IgHook::SafeData<int()> &) (hook=Unhandled dwarf expression opcode 0xfa

)
at /build/davidlt/ext/CMSSW_6_0_X/20120314_1407/a/BUILD/slc5_amd64_gcc470/external/igprof/5.9.3/igprof-5.9.3/src/profile-perf.cc:293
#5 0x0000003447067b47 in _IO_proc_open@@GLIBC_2.2.5 () from /lib64/libc.so.6
#6 0x0000003447067e39 in popen@@GLIBC_2.2.5 () from /lib64/libc.so.6
#7 0x00007f84135c46e2 in dumpAllProfiles (arg=0x7fff39bacb70)

at /build/davidlt/ext/CMSSW_6_0_X/20120314_1407/a/BUILD/slc5_amd64_gcc470/external/igprof/5.9.3/igprof-5.9.3/src/profile.cc:294
#8 0x00007f84135c4ee5 in exitDump () at /build/davidlt/ext/CMSSW_6_0_X/20120314_1407/a/BUILD/slc5_amd64_gcc470/external/igprof/5.9.3/igprof-5.9.3/src/profile.cc:425
#9 0x0000003447035d92 in exit () from /lib64/libc.so.6
#10 0x000000344701ece4 in __libc_start_main () from /lib64/libc.so.6
#11 0x0000000000406709 in _start ()

Doing

(gdb) thread info
No symbol "info" in current context.
(gdb) info threads
Id Target Id Frame
- 1 Thread 0x7f84133f1720 (LWP 31858) 0x000000344740dff4 in __lll_lock_wait () from /lib64/libpthread.so.0

Shows there is only one thread but it is stuck waiting for a mutex lock. This usually means there is a problem with a missing 'get/release' pair in the mutex.

**Comment by ktf** [comment]
v6.0.0 should have the fix for this.
